# Generated by Django 6.0.3 on 2026-04-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Food', 'Food'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Transport', 'Transport'), ('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investment', 'Investment')], max_length=50),
        ),
    ]
